Repository technance-foundation/code-style, pull requests merged in 2025-08, with the labels that each got.

#32 Setup automatic release ci
  .changeset/config.json
  .github/workflows/ci.yml
  .github/workflows/pkg-pr-new.yml
  .github/workflows/release.yml
  .nvmrc
  package.json
  pnpm-lock.yaml
Labels: Type - Feature

#34 Clean expo config to merge to react config
  src/eslint/expo.js
  src/eslint/types.d.ts
Labels: Type - Fix

#33 Reuse composite GH actions
  .github/workflows/pkg-pr-new.yml
  .github/workflows/release.yml
Labels: Type - Refactor
